# Metadata for ablation

1. Use old code from `scripts/one_beat.py` to find heartrate for each subject.
2. Keep the filters from the old code
3. Explore heart rates of the subjects

In [1]:
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df_summary = pd.read_csv('../data/beats_summary_frame.csv')
if 'Unnamed: 0' in df_summary.columns:
    df_summary = df_summary.drop(columns=['Unnamed: 0'])
df_hr = df_summary.groupby('subject')['hr'].first().reset_index()
df_hr.head()

   subject          hr
0        0   55.663204
1        1   71.964863
2        2   79.111542
3        3   75.871406
4        4  116.443278

In [3]:
# 10 seconds are represented in 4096 pixels
# So we only have 3 significant digits in the the heart rate values

In [5]:
# find how many non-unique values of hr are there
digits = 3
df_hr['hr'].round(digits).value_counts()[df_hr['hr'].round(digits).value_counts() > 1]

hr
75.464    10
70.217     8
71.029     7
77.527     6
77.834     6
          ..
90.789     2
76.308     2
73.252     2
75.946     2
74.984     2
Name: count, Length: 2872, dtype: int64

In [7]:
df_meta = pd.read_csv('../data/exams.csv')
df_16 = df_meta[df_meta['trace_file'] == 'exams_part16.hdf5'].reset_index(drop=True)
df_16.head()

,exam_id,age,is_male,nn_predicted_age,1dAVb,RBBB,LBBB,SB,ST,AF,patient_id,death,timey,normal_ecg,trace_file
0,1719487,36,True,48.075348,False,False,False,False,False,False,743857,False,1.049314,True,exams_part16.hdf5
1,1733991,66,False,40.656740,False,False,False,False,False,False,22622,NaN,NaN,False,exams_part16.hdf5
2,1801245,71,False,68.454320,False,False,False,False,False,False,825816,False,0.906849,False,exams_part16.hdf5
3,1805614,85,True,80.328300,False,False,False,False,False,False,1741484,NaN,NaN,False,exams_part16.hdf5
4,1718974,72,True,65.607850,False,False,False,False,False,False,995129,False,1.049314,False,exams_part16.hdf5

In [ ]:
df_meta